name: CI for React App

on:
  push:
    branches: ["master"] # when code is pushed

jobs:
  build-and-test:
    runs-on: windows-latest # 🚀 Windows runner for CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Check formatting with Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx

      - name: Run tests
        run: npm test

      - name: Build React app
        run: npm run build
